// <auto-generated />
using System;
using Back.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Back.Models.Cliente", b =>
                {
                    b.Property<int>("IDCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDLocalidad")
                        .HasColumnType("int");

                    b.Property<int>("LocalidadIDLocalidad")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDCliente");

                    b.HasIndex("LocalidadIDLocalidad");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Back.Models.DetalleDePedido", b =>
                {
                    b.Property<int>("IDDetalleDePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDDetalleDePedido"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IDPedido")
                        .HasColumnType("int");

                    b.Property<int>("IDProducto")
                        .HasColumnType("int");

                    b.Property<int>("PedidoIDPedido")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoIDProducto")
                        .HasColumnType("int");

                    b.HasKey("IDDetalleDePedido");

                    b.HasIndex("PedidoIDPedido");

                    b.HasIndex("ProductoIDProducto");

                    b.ToTable("DetallesDePedidos");
                });

            modelBuilder.Entity("Back.Models.EstadoDePedido", b =>
                {
                    b.Property<int>("IDEstadoDePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDEstadoDePedido"));

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("motivo_cancelacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDEstadoDePedido");

                    b.ToTable("EstadosDePedidos");
                });

            modelBuilder.Entity("Back.Models.HistorialDeEstados", b =>
                {
                    b.Property<int>("IDHistorialEstados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDHistorialEstados"));

                    b.Property<int>("EstadoDePedidoIDEstadoDePedido")
                        .HasColumnType("int");

                    b.Property<int>("IDEstadoDePedido")
                        .HasColumnType("int");

                    b.Property<int>("IDPedido")
                        .HasColumnType("int");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int");

                    b.Property<int>("PedidoIDPedido")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioIDUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fecha_hora_fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_hora_inicio")
                        .HasColumnType("datetime2");

                    b.HasKey("IDHistorialEstados");

                    b.HasIndex("EstadoDePedidoIDEstadoDePedido");

                    b.HasIndex("PedidoIDPedido");

                    b.HasIndex("UsuarioIDUsuario");

                    b.ToTable("HistorialesDeEstados");
                });

            modelBuilder.Entity("Back.Models.IntentoDeEntrega", b =>
                {
                    b.Property<int>("IDIntentoDeEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDIntentoDeEntrega"));

                    b.Property<DateTime>("FechaDeIntento")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("IDPedido")
                        .HasColumnType("int");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int");

                    b.Property<int>("PedidoIDPedido")
                        .HasColumnType("int");

                    b.Property<string>("RazonDeFallo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL_Foto_Verificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioIDUsuario")
                        .HasColumnType("int");

                    b.HasKey("IDIntentoDeEntrega");

                    b.HasIndex("PedidoIDPedido");

                    b.HasIndex("UsuarioIDUsuario");

                    b.ToTable("IntentosDeEntregas");
                });

            modelBuilder.Entity("Back.Models.Localidad", b =>
                {
                    b.Property<int>("IDLocalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDLocalidad"));

                    b.Property<string>("Barrio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDLocalidad");

                    b.ToTable("Localidades");
                });

            modelBuilder.Entity("Back.Models.Pedido", b =>
                {
                    b.Property<int>("IDPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPedido"));

                    b.Property<string>("EstadoActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEntregaEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntregaReal")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaDePago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("HoraEntregaEstimada")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraEntregaReal")
                        .HasColumnType("time");

                    b.Property<int>("IDCliente")
                        .HasColumnType("int");

                    b.Property<int>("IDEstadoDePedido")
                        .HasColumnType("int");

                    b.Property<int>("IDSucursal")
                        .HasColumnType("int");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IDPedido");

                    b.HasIndex("IDCliente");

                    b.HasIndex("IDEstadoDePedido");

                    b.HasIndex("IDSucursal");

                    b.HasIndex("IDUsuario");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Back.Models.Producto", b =>
                {
                    b.Property<int>("IDProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDProducto"));

                    b.Property<int>("CantidadProducto")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioProducto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IDProducto");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Back.Models.Sucursal", b =>
                {
                    b.Property<int>("IDSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDSucursal"));

                    b.Property<string>("Dirección")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSucursal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teléfono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDSucursal");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Back.Models.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDSucursal")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucursalIDSucursal")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUsuario");

                    b.HasIndex("SucursalIDSucursal");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Back.Models.Cliente", b =>
                {
                    b.HasOne("Back.Models.Localidad", "Localidad")
                        .WithMany("Clientes")
                        .HasForeignKey("LocalidadIDLocalidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("Back.Models.DetalleDePedido", b =>
                {
                    b.HasOne("Back.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoIDPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Back.Models.Producto", "Producto")
                        .WithMany("Detalles")
                        .HasForeignKey("ProductoIDProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Back.Models.HistorialDeEstados", b =>
                {
                    b.HasOne("Back.Models.EstadoDePedido", "EstadoDePedido")
                        .WithMany("Historiales")
                        .HasForeignKey("EstadoDePedidoIDEstadoDePedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Back.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoIDPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Back.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoDePedido");

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Back.Models.IntentoDeEntrega", b =>
                {
                    b.HasOne("Back.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoIDPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Back.Models.Usuario", "Usuario")
                        .WithMany("IntentosDeEntrega")
                        .HasForeignKey("UsuarioIDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Back.Models.Pedido", b =>
                {
                    b.HasOne("Back.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("IDCliente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Back.Models.EstadoDePedido", "EstadoDePedido")
                        .WithMany("Pedidos")
                        .HasForeignKey("IDEstadoDePedido")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Back.Models.Sucursal", "Sucursal")
                        .WithMany("Pedidos")
                        .HasForeignKey("IDSucursal")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Back.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("EstadoDePedido");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Back.Models.Usuario", b =>
                {
                    b.HasOne("Back.Models.Sucursal", "Sucursal")
                        .WithMany("Usuarios")
                        .HasForeignKey("SucursalIDSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Back.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Back.Models.EstadoDePedido", b =>
                {
                    b.Navigation("Historiales");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Back.Models.Localidad", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("Back.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Back.Models.Producto", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Back.Models.Sucursal", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Back.Models.Usuario", b =>
                {
                    b.Navigation("IntentosDeEntrega");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
