# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - farmaciaapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: azure/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # Se especifica la ruta a la carpeta Back/ donde está tu proyecto
      - name: Restore
        run: dotnet restore Back/Back.csproj

      - name: Build
        run: dotnet build Back/Back.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Back/Back.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3FFBCA370E064D29B55B039E4BEA36E4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1CC5C54007CC4CC3A58E888182A8C3A0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2A9AAC9CC2D74C98867178E1AE42F1D7 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'farmaciaapi'
          slot-name: 'Production'
          package: .
          
